branch-defaults:
  master:
    environment: Mbird-mag
environment-defaults:
  Mbird-mag:
    branch: null
    repository: null
global:
  application_name: mbird
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 7.1 running on
    64bit Amazon Linux/2.5.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
